import Head from "next/head";
import { useEffect, useState } from "react";
import * as Realm from "realm-web";
import Header from "@/components/Header";
import Container from "@/components/Container";
import Hero from "@/components/Hero";
import Category from "@/components/Category";
import Products from "@/components/Products";
import Pagination from "./../components/Pagination";
import Footer from "@/components/Footer";

export default function Home() {
	const [products, setProducts] = useState([]);
	useEffect(() => {
		async function getData() {
			const REALM_APP_ID = process.env.NEXT_PUBLIC_REALM_APP_ID; // ideally in environment variable
			const app = new Realm.App({ id: REALM_APP_ID });
			const credentials = Realm.Credentials.anonymous();
			try {
				const user = await app.logIn(credentials);
				const allProducts = await user.functions.getAllProducts();
				setProducts(allProducts);
			} catch (err) {
				console.error(err);
			}
		}
		getData();
	}, []);

	return (
		<div className="flex flex-col items-center justify-center min-h-screen py-2">
			<Head>
				<title>MongoDB E-Commerce Demo - Home</title>
				{/* <meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <h1 className="underline">Hello world!</h1> */}
			{/* <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
				{products &&
					products.map((product) => {
						return <p key={product._id}>{product.name}</p>;
					})}
			</main> */}
			<div className="bg-white w-full min-h-screen">
				<Header />
				<Container>
					<Hero />
					<Category
						category="Tech Wear"
						categoryCount={`${products.length} Products`}
					/>
					<Products products={products} />
					<Pagination />
					<Footer />
				</Container>
			</div>
		</div>
	);
}
